[gcp_service_account]

type = "service_account"
project_id = "sistema-logistico-peirano"
private_key_id = "37c2cde5ac4e6812ae83e6495b56193da8029870"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCrRqzUl2ZCUWeo
Y5WfOZuBKwDteJJIzmk2wl+WSQ8yGx+1r3keHYOGK8s+cGIe94OzkCZVxaZA0nCR
64lADzGUW8l4m04zIwYa62uBq1kVHgez9L+X6UPHEQtvNpumGVgXZpBFZiXnzWKV
PnkxAUeJLEa0hUXVhdRIT1A5bKXPvMFyTuyiKDE8F96PxqhRZ+0KBjUxssM0+KjW
rrGubouzE5kEIpEElVjjsh9jAGWKUJGOGaoCYX82q2krQflKhy8gDJQk+wea3nLO
J9/3nyZoNkfszl0pOI7XkkmeSmVkof/ZHyt0VVqUNQAC7IagTdgtw4AxYgWCQn2p
nX/hz0tLAgMBAAECggEASPAnB72VwaYzE4WdIRqCO4aZtYdEHJcyPSyXUkO4oejl
HxUj6gw9h3S879EiJ/fV8TDw8lPiUfaME8gPQeV2gqx35tGUgrhmkC4zMRxMKm8I
br1KniGrSGncybaioCBo4EZAKB2xBL71PYNGTvUxhpwBXDzpGV4NoeGM03eOQSF5
kFkKsgM9bkA+YmgQTZ5J11wzDNI5db/8aMqz+tJiDC3ESTck6N1mQwNVVTCRP51n
QgPeGRUeU/H9yMJah+Fg4jtGHhTAMA49I1KlbhIBHbcItTq/YDxbv6+wQwx0NA5q
x1cZ3GXpvOu27tVUe/juAqQNrw/vNpc0cFuXaD4XoQKBgQDT3BOV7KLRdP5G3PBE
QOZCgKXxM4JKgAIBmtmoXVkEi4jticZqBDbXTVaZwZVDXS7sUzAaBbUsEPwb4n4z
MbA7BDtOqDWp3/SQBO/oHIh2bEIbpX/X/CEZih97lvj44lzxgmP1YR7dHwGh/oNZ
zE+7wND/c9AMIQhg5c5XsvPV0QKBgQDO9f+BR2dZEWkmhS5U+BxnpMGOa3X4YamS
6LxmlGFxMJ/TsOyaNcdd8p6zDtcVJkFPhqsTwxNzB+OWrVLM8mXY+GZ9PFDaOS4/
fTA4NGYe/DfrHQ2gkN18sf7Hurg/RhUJ4hML/tVQRleu5ZQ/PnlttWIc6c3n5FGm
L0RI8K4qWwKBgQCAj2bPLpaq1fzLUZz3Pg68QkbwdBpXTRBqmuYDtgmjqWzBAD8H
7GC/C+5GRWNnSm+D9wMUd2w2PmROI4YDWN6hIXM/yvEtkXpdvrE6P75LZmxDTI2k
qhoH3no2TCnvFaXi5AX2TCYndn5OKBza7BFiVKI+sa+I/K6R5kHtk+lFUQKBgQC9
QSNG+x68yjkXqo410TVYacc+D3Kvkc9Zsk4ml+WLdmWRVabnVepcNPN+1kFE69ip
eoKS7b6pYDt0nEatd7Q+9tfyCef9xnBOSpJ/sxr3lrkj3UuK2y5PSw2rY0n9Qn8W
rI+yVnSGley02Of59Y1hD48K1ZsfRSCNEYgmE0GRJQKBgQDGBupwvG1xz+C+JdlQ
9cuo7l+Rrwcb3YGNGkLatKUK+cu48b5Q3mHTApBi4ezbPLVel2M1pBjHn5JPWCDf
1VssAu5hcOIDQ760Ews60DbDQaLZmKB9jFU2DUASYGoA+pPxl32TvuVFUcmtecTJ
JPyX6gUfkZNHgHZdHTSK9+6h5w==
-----END PRIVATE KEY-----
"""
client_email = "streamlit-drive@sistema-logistico-peirano.iam.gserviceaccount.com"
client_id = "107061693418393319874"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-drive%40sistema-logistico-peirano.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
