[usuarios.ivan]
nombre = "Iván"
password = "0802"
rol = "admin"

[usuarios.gerencia]
nombre = "Gerencia"
password = "Queija01"
rol = "gerencia"

[usuarios.logistica]
nombre = "Logística"
password = "Depo01"
rol = "logistica"

[usuarios.supervisor]
nombre = "Supervisor"
password = "Super01"
rol = "supervisor"

[usuarios.contabilidad]
nombre = "Administración"
password = "Admin01"
rol = "contabilidad"